/**
 * Build script to generate all city pages
 * This script can be run to pre-generate content for all cities
 * Run: npm run generate
 * 
 * Note: This script pre-generates AI content. The actual static pages
 * are generated by Next.js during `npm run build` via generateStaticParams()
 */

import { getAllCitiesSync, getAllStates } from '../lib/cities';
import { generateCityContent } from '../lib/content-generator';
import fs from 'fs';
import path from 'path';

interface GenerationStats {
  total: number;
  processed: number;
  errors: number;
  skipped: number;
  startTime: number;
}

async function generateAllPages() {
  console.log('🚀 Starting content generation...\n');
  
  const cities = getAllCitiesSync();
  const states = getAllStates();
  const totalCities = cities.length;
  
  const stats: GenerationStats = {
    total: totalCities,
    processed: 0,
    errors: 0,
    skipped: 0,
    startTime: Date.now(),
  };

  // Check if OpenAI API key is configured
  if (!process.env.OPENAI_API_KEY) {
    console.warn('⚠️  OPENAI_API_KEY not found. Content will use fallback templates.');
    console.warn('   Set OPENAI_API_KEY in .env.local to generate AI content.\n');
  }

  console.log(`📊 Statistics:`);
  console.log(`   - Total cities: ${totalCities}`);
  console.log(`   - Total states: ${states.length}`);
  console.log(`   - Average cities per state: ${Math.round(totalCities / states.length)}\n`);

  // Generate content for each city
  for (let i = 0; i < cities.length; i++) {
    const city = cities[i];
    try {
      const content = await generateCityContent(city);
      stats.processed++;
      
      // Progress indicator
      if ((i + 1) % 10 === 0 || i === cities.length - 1) {
        const progress = ((i + 1) / totalCities * 100).toFixed(1);
        console.log(`   Progress: ${i + 1}/${totalCities} (${progress}%) - Last: ${city.name}, ${city.stateAbbr}`);
      }
      
      // Small delay to avoid rate limiting (only if OpenAI is configured)
      if (process.env.OPENAI_API_KEY) {
        await new Promise(resolve => setTimeout(resolve, 100));
      }
    } catch (error) {
      stats.errors++;
      console.error(`   ❌ Error processing ${city.name}, ${city.stateAbbr}:`, error);
    }
  }

  const duration = ((Date.now() - stats.startTime) / 1000).toFixed(2);
  
  console.log(`\n✅ Content generation complete!`);
  console.log(`   - Processed: ${stats.processed}/${stats.total}`);
  console.log(`   - Errors: ${stats.errors}`);
  console.log(`   - Duration: ${duration}s`);
  console.log(`\n📝 Next steps:`);
  console.log(`   1. Run 'npm run build' to generate static pages`);
  console.log(`   2. Pages will be generated at build time via generateStaticParams()`);
  console.log(`   3. For 5,000+ cities, build may take 30-60 minutes\n`);
}

// Run the generator
generateAllPages().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});

